name: get players
on:
   schedule:
    - cron: '31 1 * * *'  # every day at 01:31

jobs:
  add-to-sheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run getPlayers
