name: gsheet.action test
on: push

jobs:
  add-to-sheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm start 
      - id: set_var
        run: | 
          content=`cat 1.json`
          echo "::set-output name=scores::$content"
          echo "$content"
      - run: |
          echo ${{steps.set_var.outputs.scores}}
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.0.0
        with:
          spreadsheetId: 1NpSCP40KtCK8ClPH8WzE__VYZm0v4sd_2-BpZcPSRV4
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getWorksheet", "args": { "worksheetTitle": "Sheet1" }},
              { "command": "updateData", "args": { "data": ${{steps.set_var.outputs.scores}}, "minRow": "2", "minCol": "2"}}
            ] 
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
